language: node_js
env:
  - REDIS_CLUSTER=127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005

node_js:
  - "6"
  - "7"
  - "8"
  - "9"

install:
  make travis-install

script: make travis-run

after_script: npm run coverage

cache:
  directories:
    - "node_modules"
#    - "redis-3.2.11"

services:
  - redis-server