language: node_js
env:
  - REDIS_CLUSTER=127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005

node_js:
  - "6"
  - "7"
  - "8"

install:
  make travis-install

script: make travis-run

cache:
  directories:
    - "node_modules"

services:
  - redis-server